// <auto-generated />
using System;
using MIS_Cuidados_Criticos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MIS_Cuidados_Criticos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501190135_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Nivel_criticidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.AlertaPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertaId")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Paciente")
                        .HasColumnType("integer");

                    b.Property<int>("Id_alerta")
                        .HasColumnType("integer");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.HasIndex("Id_Paciente");

                    b.HasIndex("Id_alerta");

                    b.HasIndex("PacienteId");

                    b.ToTable("AlertaPacientes");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Nomre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.SignoAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertaId")
                        .HasColumnType("integer");

                    b.Property<int>("Id_alerta")
                        .HasColumnType("integer");

                    b.Property<int>("Id_signo_vital")
                        .HasColumnType("integer");

                    b.Property<int?>("SignoVitalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.HasIndex("Id_alerta");

                    b.HasIndex("Id_signo_vital");

                    b.HasIndex("SignoVitalId");

                    b.ToTable("SignoAlertas");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.SignoPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha_hora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_paciente")
                        .HasColumnType("integer");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("SignoVitalId")
                        .HasColumnType("integer");

                    b.Property<int>("id_signo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_paciente");

                    b.HasIndex("PacienteId");

                    b.HasIndex("SignoVitalId");

                    b.HasIndex("id_signo");

                    b.ToTable("SignoPacientes");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.SignoVital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<int>("Frecuencia_cardiaca")
                        .HasColumnType("integer");

                    b.Property<string>("Presion_arterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Saturacion_oxigeno")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SignosVitales");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.AlertaPaciente", b =>
                {
                    b.HasOne("MIS_Cuidados_Criticos.Dominio.Alerta", null)
                        .WithMany("AlertaPacientes")
                        .HasForeignKey("AlertaId");

                    b.HasOne("MIS_Cuidados_Criticos.Dominio.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("Id_Paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MIS_Cuidados_Criticos.Dominio.Alerta", "alerta")
                        .WithMany()
                        .HasForeignKey("Id_alerta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MIS_Cuidados_Criticos.Dominio.Paciente", null)
                        .WithMany("AlertaPacientes")
                        .HasForeignKey("PacienteId");

                    b.Navigation("alerta");

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.SignoAlerta", b =>
                {
                    b.HasOne("MIS_Cuidados_Criticos.Dominio.Alerta", null)
                        .WithMany("SignoAlertas")
                        .HasForeignKey("AlertaId");

                    b.HasOne("MIS_Cuidados_Criticos.Dominio.Alerta", "Alerta")
                        .WithMany()
                        .HasForeignKey("Id_alerta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MIS_Cuidados_Criticos.Dominio.SignoVital", "SignoVital")
                        .WithMany()
                        .HasForeignKey("Id_signo_vital")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MIS_Cuidados_Criticos.Dominio.SignoVital", null)
                        .WithMany("signoAlertas")
                        .HasForeignKey("SignoVitalId");

                    b.Navigation("Alerta");

                    b.Navigation("SignoVital");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.SignoPaciente", b =>
                {
                    b.HasOne("MIS_Cuidados_Criticos.Dominio.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("Id_paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MIS_Cuidados_Criticos.Dominio.Paciente", null)
                        .WithMany("SignoPacientes")
                        .HasForeignKey("PacienteId");

                    b.HasOne("MIS_Cuidados_Criticos.Dominio.SignoVital", null)
                        .WithMany("signopacientes")
                        .HasForeignKey("SignoVitalId");

                    b.HasOne("MIS_Cuidados_Criticos.Dominio.SignoVital", "signoVital")
                        .WithMany()
                        .HasForeignKey("id_signo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paciente");

                    b.Navigation("signoVital");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.Alerta", b =>
                {
                    b.Navigation("AlertaPacientes");

                    b.Navigation("SignoAlertas");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.Paciente", b =>
                {
                    b.Navigation("AlertaPacientes");

                    b.Navigation("SignoPacientes");
                });

            modelBuilder.Entity("MIS_Cuidados_Criticos.Dominio.SignoVital", b =>
                {
                    b.Navigation("signoAlertas");

                    b.Navigation("signopacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
